# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      "GitHub Actions updates":
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/percona"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/mysql"
    schedule:
      interval: "monthly"