version: '2'

services:
    php:
        build: ./${PHP_VERSION}
        container_name: php
        volumes_from:
            - source
        ports:
            - '9000:9000'
        links:
            - mysql
            - memcached
        networks:
            - bitrix
        restart: always
    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: webserver
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '80:80'
            - '443:443'
        links:
            - php
        networks: 
            - bitrix
        restart: always
    mysql:
        build: ./${DB_SERVER_TYPE}
        container_name: mysql
        volumes_from:
            - source
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - bitrix
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: memcached
        volumes_from:
            - source
        ports:
            - '11211:11211'
        networks:
            - bitrix
        restart: always
    source:
        image: alpine:latest
        container_name: source
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/${DB_SERVER_TYPE}:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - ./data/${DB_SERVER_TYPE}:/var/lib/mysql
            - ./data/memcached:/var/lib/memcached
            # - ./logs:/var/www/bitrix
            - ./www/html:/var/www/html
            - ./www/html:/var/www/bitrix
            # - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        networks:
            - bitrix
networks:
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24
